## 📚 Importing Libraries


In [1]:
import cv2

In [2]:
import numpy as np
import warnings
warnings.simplefilter("ignore")

## 🖼️ Loading and Displaying Images


In [3]:
img=cv2.imread("Images/Cristiano_Ronaldo.jpg",1)

In [4]:
print(img)

[[[244 243 245]
  [244 243 245]
  [244 243 245]
  ...
  [242 244 245]
  [242 244 245]
  [242 244 245]]

 [[244 243 245]
  [244 243 245]
  [244 243 245]
  ...
  [242 244 245]
  [242 244 245]
  [242 244 245]]

 [[244 243 245]
  [244 243 245]
  [244 243 245]
  ...
  [242 244 245]
  [242 244 245]
  [242 244 245]]

 ...

 [[222 220 219]
  [222 220 219]
  [222 220 219]
  ...
  [230 228 227]
  [230 228 227]
  [228 226 225]]

 [[222 220 219]
  [222 220 219]
  [222 220 219]
  ...
  [230 228 227]
  [230 228 227]
  [228 226 225]]

 [[222 220 219]
  [222 220 219]
  [222 220 219]
  ...
  [230 228 227]
  [230 228 227]
  [228 226 225]]]


In [5]:
img.shape

(1920, 1920, 3)

In [6]:
cv2.imshow("Cr7",img)#displaying the image
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [7]:
## Image Preprocessing -
img=cv2.imread("Images/Cristiano_Ronaldo.jpg")
resized_img=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_img,cv2.COLOR_BGR2GRAY)
cv2.imshow("Cr7",gray)
cv2.waitKey()
cv2.destroyAllWindows()

## 😺 Face Detection using Haar Cascade

In [9]:
face_classifier=cv2.CascadeClassifier("Haarcascades/haarcascade_frontalface_default.xml")
image=cv2.imread("Images/Cristiano_Ronaldo.jpg")
image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces=face_classifier.detectMultiScale(gray,1.05,5)

In [10]:
print(faces)

[[137  84 221 221]]


In [11]:
if faces is ():
    print("No faces is found")
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),1) # Thickness
    
cv2.imshow("Face Detection",image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

## Face 😺 along with👁️ Eye Detection using Haar Cascade

In [15]:
face_classifier=cv2.CascadeClassifier("Haarcascades/haarcascade_frontalface_default.xml")
face_eye=cv2.CascadeClassifier("Haarcascades/haarcascade_eye.xml")
image=cv2.imread("Images/Cristiano_Ronaldo.jpg")
resized=cv2.resize(image,(500,500))
gray=cv2.cvtColor(resized,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.3,5)
if faces is ():
    print("No faces is found")
for (x,y,w,h) in faces:
    cv2.rectangle(resized,(x,y),(x+w,y+h),(0,255,100),1)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resized[y:y+h,x:x+w]
    eyes=face_eye.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow("Face Detection",resized)
cv2.waitKey()
cv2.destroyAllWindows()